name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: go build

      - name: uplaod
        uses: actions/upload-artifact@v2
        with:
          name: tcp_proxy
          path: ./tcp_proxy